-- Healthcare AI Demo - Database Cleanup Script
-- Run this script to remove unused tables from the database
-- ================================================================

USE DATABASE HEALTHCARE_DEMO;
USE SCHEMA MEDICAL_NOTES;

-- Drop unused tables that were never populated or used by the application
DROP TABLE IF EXISTS COHORT_INSIGHTS;
DROP TABLE IF EXISTS PHYSICIAN_INSIGHTS;

-- Verify cleanup
SELECT 'Cleanup completed. Remaining tables:' as STATUS;

-- List remaining tables
SHOW TABLES;

-- Verify core tables still exist with data
SELECT 'PATIENT_ANALYSIS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM PATIENT_ANALYSIS
UNION ALL
SELECT 'MEDICATION_ANALYSIS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM MEDICATION_ANALYSIS
UNION ALL
SELECT 'COST_ANALYSIS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM COST_ANALYSIS
UNION ALL
SELECT 'REALTIME_ANALYSIS_LOG' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM REALTIME_ANALYSIS_LOG
UNION ALL
SELECT 'PROCESSING_STATUS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM PROCESSING_STATUS
UNION ALL
SELECT 'DEMO_SCENARIOS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DEMO_SCENARIOS
UNION ALL
SELECT 'PROCEDURE_COSTS' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM PROCEDURE_COSTS
UNION ALL
SELECT 'DRUG_INTERACTIONS_REFERENCE' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DRUG_INTERACTIONS_REFERENCE
ORDER BY TABLE_NAME;
